### ISSUE TITLE
NuGet balíček

### ISSUE THREAD

**Issue by michalblaha** [HlidacStatu/API#3]
Hodne by pomohl  NuGet baliček pro .NET Framework i .NET Core...

**Comment by rpliva** [comment]
Pripravil jsem projekt s podporou pro .NET Standard 1.6 i .NET Framework 4.6.2 viz https://github.com/HlidacStatu/API/pull/4. NuGet balicek pak bude obsahovat knihovnu pro oba frameworky. Po zameregovani ji nahraju do NuGet repository s verzi 1.1.0

**Comment by michalblaha** [comment]
Díky
