### ISSUE TITLE
V api v2 chybí určený datového typu

### ISSUE THREAD

**Issue by suchoss** [HlidacStatu/API#5]
Ahoj, například tady není určen datový typ (ale těch výskytů je víc):

https://github.com/HlidacStatu/API/blob/58d66fcd2a25d11c4578d8cd2729f643e3fe2c4f/v2/openapi.yaml#L889-L890

**Comment by suchoss** [comment]
Datové typy vygeneruju až z hotového api

**Comment by marousekJakub** [comment]
U některých typů jsem zkoumal u Michala, co přesně znamenají, ale nedostal jsem odpověď :-) takže to vyřešit, až to bude implementované
