### ISSUE TITLE
verzování API

### ISSUE THREAD

**Issue by suchoss** [HlidacStatu/API#6]
Ahoj,

upřímně nevím, jestli verzování s tečkama je správně (ještě nikdy jsem to neviděl a přijde mi to divné). 

https://github.com/HlidacStatu/API/blob/58d66fcd2a25d11c4578d8cd2729f643e3fe2c4f/v2/openapi.yaml#L5-L10

Při představě, že mám část API volanou `http://www.hlidacstatu.cz/api/v2.0.0`, část `http://www.hlidacstatu.cz/api/v2.0.1`, část `http://www.hlidacstatu.cz/api/v2.3.4`, mi nabíhá husí kůže. 

Vždy jsem viděl verzovanou jen Major verzi (breaking changes). 

Názory?

**Comment by suchoss** [comment]
Bude vytvořeno bez teček

**Comment by marousekJakub** [comment]
Souhlasím s tím, aby to bylo bez teček. Myslím, že jsem tuhle specifikaci začal z nějaké šablony, možná proto jsem to tam nechal.
